site_name: Gonzalez Analytics
theme:
  name: 'windmill'
  features:
    - navigation.tabs
    - navigation.sections
    ###Make nav bars sticky
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Darkside Mode
      primary: orange
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: The force is with you mode    
      primary: blue
      accent: orange


extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gonzalezben81
    - icon: fontawesome/brands/twitter
      link: https://github.com/gonzalezben81
    - icon: fontawesome/brands/linkedin
      link: https://github.com/gonzalezben81

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/gonzalezben81"  target="_blank" rel="noopener">Ben Gonzalez</a>  