---
title: "Romeo and Juliet"
author: "Ben Gonzalez"
date: "June 29, 2016"
output: html
---

```{r setup, include=FALSE}
library(Rcampdf)
library(tm)
library(wordcloud)
library(ggplot2)
library(biclust)
library(igraph)


##Set the file path for the documents to be inspected############################################
actone <- ("C:/Users/stlgonzb/Desktop/texts")   
actone 

##Sets the directory to arbitrary name in ()#####################################
dir(actone) 


library(tm)   
docs <- Corpus(DirSource(actone))   

##Summary of the docs object ##########################################################
summary(docs)  
inspect(docs[1])



docs <- tm_map(docs, tolower) 
docs


##Removes the whitespace in the document being inspected##############################
docs <- tm_map(docs, stripWhitespace)


#fix(docs)

docs <- tm_map(docs, PlainTextDocument) 


dtm <- DocumentTermMatrix(docs)   
dtm  


##Finds the frequency of the terms in a text document########################
findFreqTerms(dtm,10)


##Finds term correlations with other terms#########################################
findAssocs(dtm, "gun", 0.4)

##Removes sparse terms from a document#########################################################
inspect(removeSparseTerms(dtm, 0.6))

tdm <- TermDocumentMatrix(docs)   
tdm 

freq <- colSums(as.matrix(dtm))   
length(freq) 

ord <- order(freq) 

m <- as.matrix(dtm)   
dim(m)   
write.csv(m, file="dtm.csv") 


dtms <- removeSparseTerms(dtm, 0.1)    
inspect(dtms) 


freq[head(ord)] 

freq[tail(ord)]  


head(table(freq), 20) 

tail(table(freq), 20) 


freq <- colSums(as.matrix(dtms))   
freq  
knitr::opts_chunk$set(echo = FALSE)
```

##Romeo and Juliet- Word appears 10 times

```{r echo =FALSE,results='hide',message=FALSE}
##Plots the minimum number (frequency) of words in color
set.seed(142)   
wordcloud(names(freq), freq, min.freq=10, scale=c(5, .1), colors=brewer.pal(6, "Dark2"))  

```

##Romeo and Juliet- Word appears 30 times

```{r echo=FALSE,results='hide',message=FALSE}
set.seed(142)   
wordcloud(names(freq), freq, min.freq=30, scale=c(5, .1), colors=brewer.pal(6, "Dark2")) 
```

##Romeo and Juliet- Word appears 50 times

```{r}
set.seed(142)   
wordcloud(names(freq), freq, min.freq=50, scale=c(5, .1), colors=brewer.pal(6, "Dark2")) 
```

##Romeo and Juliet- Word appears 75 times

```{r}
set.seed(142)   
wordcloud(names(freq), freq, min.freq=75, scale=c(5, .1), colors=brewer.pal(6, "Dark2")) 
```

##Romeo and Juliet- Word appears 100 times

```{r}
set.seed(142)   
wordcloud(names(freq), freq, min.freq=100, scale=c(5, .1), colors=brewer.pal(6, "Dark2")) 
```

